linters:
  enable:
    - gofmt
    - govet
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign
    - typecheck
    - misspell
    - gocyclo
    - gosec
    - unconvert
    - goconst
    - prealloc

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3

run:
  tests: true
