name: ci-tests

on:
  pull_request:
    paths-ignore:
      - "docs/**"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main

jobs:
  ci-tests:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.12"

      - name: Setup Go 1.24.x
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache-dependency-path: go.sum

      - name: Build project
        run: corepack enable && task build

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7.0.0

      - name: Install SQLite
        run: sudo apt-get update && sudo apt-get install -y sqlite3 libsqlite3-dev

      - name: Run Tests
        run: go test -v ./...
